### ISSUE TITLE
Customization of the timestamp format

### ISSUE THREAD

**Issue by rdewaele** [martincostello/xunit-logging#311]
**Is your feature request related to a problem? Please describe.**
The current timestamp format (e.g. `[2022-05-17 00:08:36Z]`) does not have sub-second timing information, which limits the diagnostic potential of the timestamp.

**Describe the solution you'd like**
If customization of the log format is currently possible, I missed it.
In this event, I would like to both apologize and suggest adding an example describing this use-case.

The following solutions have crossed my mind:
- The problem is my ignorance, in which case I refer to the statement above.
- A hard-coded format change seems adequate, but perhaps a missed opportunity.
- Customization of the timestamp format, either through code or configuration.
- Customization of the log format as a whole sounds like a nice bonus.

**Describe alternatives you've considered**
Adding timestamps to the log messages themselves is of course functional, but rather inelegant.
( Okay, I'll admit that this issue is hardly a blocker, but ... elegance! :sweat_smile: . )

Thank you for your consideration, and this very useful library.

**Comment by martincostello** [comment]
Thanks for your suggestion @rdewaele! I've opened a PR to implement this in #313.

Could you take a look and see if it would work as you'd envisioned? You'd be able to configure a different format for the timestamps like this:

https://github.com/martincostello/xunit-logging/blob/e8c828ad155ab0c33003cbc604d249e734b45757/tests/Logging.XUnit.Tests/IntegrationTests.cs#L177-L183

The default behaviour would be the same as it is in the existing versions, which is to use the [`"u"`](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#UniversalSortable) format string.

**Comment by rdewaele** [comment]
Thanks a lot for the incredibly quick implementation. I will be experimenting with it today.

Thanks!

**Comment by rdewaele** [comment]
This implementation covers all my (current ;-)) use-cases, so I am a happy camper. :+1: 

Thanks again. :-)

**Comment by martincostello** [comment]
Great thanks, I'll release this to NuGet later on today.
