### ISSUE TITLE
Serilog support

### ISSUE THREAD

**Issue by mehdihadeli** [martincostello/xunit-logging#320]
Hi,
Thanks for this useful package.
Does it work with serilog or just work with Microsoft built-in log?

**Comment by martincostello** [comment]
This library just extends the `Microsoft.Extensions.Logging` abstraction.

If you want to plug `ITestOutputHelper` into Serilog, you can use another project such as [trbenning/serilog-sinks-xunit](https://github.com/trbenning/serilog-sinks-xunit).

**Comment by mehdihadeli** [comment]
@martincostello Thanks for your response, Yes currently I use it :)
