### ISSUE TITLE
Support xunit v3

### ISSUE THREAD

**Issue by martincostello** [martincostello/xunit-logging#717]
### Is your feature request related to a problem? Please describe.

Add support for xunit v3: [_What's New in v3_](https://xunit.net/docs/getting-started/v3/whats-new)

### Describe the solution you'd like

The ability to log to the relevant primitives when targeting xunit v3.

[_Migrating from v2 to v3_](https://xunit.net/docs/getting-started/v3/migration)

**Comment by teneko** [comment]
Thanks for migrating to v3 in the near future.

During that migration here a quick work around to get the console output:
- migrate to xUnit v3 by following [What's New in v3](https://xunit.net/docs/getting-started/v3/whats-new)
- use `[assembly: CaptureTrace]` to capture `Debug.Write` and `Debug.Trace`
- and instruct the logger factory to output to Debug (not Console), for example:

```
LoggerFactory.Create(static x => {
    x.AddDebug();
    // ...
})
```

and use that logger factory in a class fixture or test classes.
